apiVersion: v1
kind: Pod
metadata:
  labels:
    app: task1-app
  name: task1
spec:
  containers:
  - image: longehdocker/task1jenk
    imagePullPolicy: IfNotPresent
    name: task1
    env:
      - name: YOUR_NAME
        value: QA-Kubernetes
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: task1-app
    name: task1-service
spec:
  type: LoadBalancer
  selector:
    app: task1-app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5500
  
    
  
   